ALTER TABLE lu_config ADD COLUMN init_screen VARCHAR DEFAULT NULL;
ALTER TABLE lu_config ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE lu_config ADD COLUMN notify_all BOOLEAN NOT NULL DEFAULT FALSE;
